name: "✨ Enhancement Request"
description: Suggest an enhancement or improvement to existing functionality
title: "[Enhancement]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest an enhancement! This form is for improvements to existing features.
        For entirely new features, please use the Feature Request template.

  - type: textarea
    id: current-behavior
    attributes:
      label: Current Behavior
      description: Describe how the feature currently works
      placeholder: "Currently, the system does..."
    validations:
      required: true

  - type: textarea
    id: proposed-enhancement
    attributes:
      label: Proposed Enhancement
      description: Describe your proposed improvement in detail
      placeholder: "I propose that we enhance this by..."
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why would this enhancement be valuable? What problems does it solve?
      placeholder: "This enhancement would help because..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: "I've considered..."

  - type: dropdown
    id: impact
    attributes:
      label: Expected Impact
      description: How many users/developers would benefit from this enhancement?
      options:
        - Low - Affects specific edge cases
        - Medium - Affects a moderate number of users
        - High - Affects most users
        - Critical - Blocks common workflows
    validations:
      required: true

  - type: dropdown
    id: breaking-change
    attributes:
      label: Breaking Change
      description: Would this enhancement require breaking changes?
      options:
        - "No"
        - "Yes"
        - "Unsure"
    validations:
      required: true

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Are you willing to help implement this enhancement?
      options:
        - label: I am willing to submit a PR for this enhancement
        - label: I would need guidance on implementation
        - label: I can help test the implementation

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/zopiolabs/zopio/blob/main/.github/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true