name: 'PR Size Check'

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-pr-size:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Check PR size
      uses: actions/github-script@v7
      with:
        script: |
          const { data: pullRequest } = await github.rest.pulls.get({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: context.issue.number
          });

          const additions = pullRequest.additions;
          const deletions = pullRequest.deletions;
          const totalChanges = additions + deletions;
          const changedFiles = pullRequest.changed_files;

          console.log(`PR Stats:`);
          console.log(`- Total changes: ${totalChanges} (${additions} additions, ${deletions} deletions)`);
          console.log(`- Changed files: ${changedFiles}`);

          // File limit check
          if (changedFiles > 50) {
            core.setFailed(`❌ PR changes too many files (${changedFiles} files). Maximum allowed: 50 files.`);
            return;
          }

          // Line change limits
          const softLimit = 500;
          const hardLimit = 2000;

          let comment = '';
          
          if (totalChanges > hardLimit) {
            core.setFailed(`❌ PR is too large (${totalChanges} lines changed). Maximum allowed: ${hardLimit} lines.`);
            comment = `### ❌ PR Size Check Failed\n\nThis PR changes ${totalChanges} lines across ${changedFiles} files, exceeding the hard limit of ${hardLimit} lines.\n\nPlease split this PR into smaller, more focused changes.`;
          } else if (totalChanges > softLimit) {
            core.warning(`⚠️ PR is large (${totalChanges} lines changed). Consider splitting it into smaller PRs.`);
            comment = `### ⚠️ PR Size Warning\n\nThis PR changes ${totalChanges} lines across ${changedFiles} files, exceeding the soft limit of ${softLimit} lines.\n\nWhile not required, consider splitting this into smaller PRs for easier review.`;
          } else {
            console.log(`✅ PR size is acceptable.`);
            comment = `### ✅ PR Size Check Passed\n\nThis PR changes ${totalChanges} lines across ${changedFiles} files.`;
          }

          // Post comment
          await github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
            body: comment
          });
